common: &common
    access_key_id: AKIAIWWQF5REKTC4ZYGQ
    secret_access_key: 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

development:
    <<: *common
    bucket: agraseva

test:
    <<: *common
    bucket: agraseva

production:
    <<: *common
    bucket: agraseva